### ISSUE TITLE
error "pkg_resources.DistributionNotFound: beautifulsoup4" when trying to run topy

### ISSUE THREAD

**Issue by chopeen** [intgr/topy#15]
I have installed topy and I keep getting the following error when I try to run "topy.exe c:\temp\typos.txt":

    c:\PythonPortable\App\Scripts>topy.exe c:\temp\typos.txt
    Traceback (most recent call last):
      File "c:\PythonPortable\App\Scripts\topy-script.py", line 5, in <module>
        from pkg_resources import load_entry_point
      File "c:\PythonPortable\App\lib\site-packages\pkg_resources.py", line 2603, in <module>
        working_set.require(__requires__)
      File "c:\PythonPortable\App\lib\site-packages\pkg_resources.py", line 666, in require
        needed = self.resolve(parse_requirements(requirements))
      File "c:\PythonPortable\App\lib\site-packages\pkg_resources.py", line 565, in resolve
        raise DistributionNotFound(req)  # XXX put more info here
    pkg_resources.DistributionNotFound: beautifulsoup4

I tried on Linux too and got the same error.

**Comment by intgr** [comment]
You have to install the dependencies, which include `beautifulsoup4`.

**Comment by chopeen** [comment]
It is installed:

    c:\PythonPortable\App\Scripts>pip install beautifulsoup4
    Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in c:\pythonportable\app\lib\site-packages

Also I think "pip" installs it automatically along with "topy".

**Comment by intgr** [comment]
This stack trace shows that it never actually gets to Topy code, so the problem is somwhere else -- maybe in Portable Python, maybe in pkg_resources. I've never used Portable Python and I don't have Windows, so I can't help you there.

If you can explain to me how to reproduce this on Linux, then maybe I could help.

**Comment by chopeen** [comment]
The same thing happens when I use Linux:

    $ pip install --user topy
    You are using pip version 6.0.8, however version 7.1.2 is available.
    You should consider upgrading via the 'pip install --upgrade pip' command.
    Collecting topy
      Using cached topy-0.2.0.tar.gz
    Requirement already satisfied (use --upgrade to upgrade): regex in ./.local/lib/python2.6/site-packages (from topy)
    Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in ./.local/lib/python2.6/site-packages (from topy)
    Installing collected packages: topy
      Running setup.py install for topy
        Installing topy script to /home/users/some_user/.local/bin
    Successfully installed topy-0.2.0

    $ ./.local/bin/topy
    Traceback (most recent call last):
      File "./.local/bin/topy", line 5, in <module>
        from pkg_resources import load_entry_point
      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2655, in <module>
        working_set.require(__requires__)
      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 648, in require
        needed = self.resolve(parse_requirements(requirements))
      File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 546, in resolve
        raise DistributionNotFound(req)
    pkg_resources.DistributionNotFound: beautifulsoup4

I am installing "topy" in my home folder. Can this be a problem?

**Comment by intgr** [comment]
Works for me on my Arch Linux machine...
```
% pip install --user topy                                                                                                    @~
Collecting topy
  Downloading topy-0.2.0.tar.gz (116kB)
    100% |████████████████████████████████| 118kB 2.4MB/s 
Collecting regex (from topy)
  Downloading regex-2015.11.22.tar.gz (574kB)
    100% |████████████████████████████████| 577kB 1.2MB/s 
Requirement already satisfied (use --upgrade to upgrade): beautifulsoup4 in /usr/lib/python3.5/site-packages (from topy)
Installing collected packages: regex, topy
  Running setup.py install for regex
  Running setup.py install for topy
Successfully installed regex topy
% ~/.local/bin/topy                                                                                                          @~
No paths specified
Usage: topy [options] FILES/DIRS...

Options:
  -h, --help            show this help message and exit
  -q, --quiet           silence information messages
  -a, --apply           overwrite files in place
  -r FILE, --rules=FILE
                        specify custom ruleset file to use
```

Perhaps try upgrading your pip? `pip install --upgrade --user pip`

**Comment by intgr** [comment]
From your message...
>   File "/usr/lib/**python2.6**/site-packages/pkg_resources.py", line 2655, in <module>

Erm... Sorry, Python 2.6 is not supported by Topy anyway. Python 2.6 was released over 7 years ago. Are you using some prehistoric "enterprise" Linux distribution?

**Comment by chopeen** [comment]
Yes and that's probably the reason. I will switch to a VM with a current version Python. Thanks for taking your time to analyze the problem.
