### ISSUE TITLE
UTF-8

### ISSUE THREAD

**Issue by kimstik** [intgr/topy#33]
write encoding is not specified on "--apply" .
I guess f.write encoding should match to f.read :

>        if opts.apply:
>            log.info("Writing %s", safe_name)
>            with open(filename, 'w', encoding='utf-8') as f:
>                f.write(text)

**Comment by intgr** [comment]
When a file is opened in text mode, Python defaults to UTF-8 already. But sure, doesn't hurt to change it for consistency.
